<a href="https://colab.research.google.com/github/ev-greshkina/DataAnalyst-educational-course/blob/main/%D0%94%D0%97_%D0%BA_%D0%BB%D0%B5%D0%BA%D1%86%D0%B8%D0%B8_19_v_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Заменить пропуски в поле Age (датасет Titanic) на медианные значения в группах пол-класс обслуживания, посмотреть качество на метриках.

**Решение вручную**

In [ ]:
# Загрузка библиотек
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import f1_score, precision_score, recall_score, accuracy_score

In [ ]:
# Получение иходных данных
url = 'https://raw.githubusercontent.com/ev-greshkina/DataAnalyst-educational-course/main/Titanic-Dataset.csv'
df = pd.read_csv(url)
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [ ]:
# Просмотр данных о наличии и количестве пропусков в столбцах
# (необязательное действие, для оценки значений при разработке)
df.isna().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [ ]:
# Получить медианные значения возраста пассажиров, в разрезах пола и класса обслуживания
df.groupby(['Sex', 'Pclass'])['Age'].median()

Sex     Pclass
female  1         35.0
        2         28.0
        3         21.5
male    1         40.0
        2         30.0
        3         25.0
Name: Age, dtype: float64

In [ ]:
# Замена пропусков на медианные значения в группах пол-класс обслуживания
for (sex, pclass), group in df.groupby(['Sex', 'Pclass']):
    median_age = group['Age'].median()
    df.loc[(df['Sex'] == sex) & (df['Pclass'] == pclass) & (df['Age'].isnull()), 'Age'] = median_age

In [ ]:
# Замена пропусков в соблбце Embarked на наиболее частое значение стоблбца Embarked ('S')
df.loc[df.Embarked.isna(), 'Embarked'] = 'S'

In [ ]:
# Повторная проверка наличия пропусков в столбецах Age и Embarked.
# На данном этапе количество пропусков должно быть равным 0
df.isna().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age              0
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         0
dtype: int64

In [ ]:
# Замена значений в столбце Sex на числовые
# Значениею male присвоить число 0, значению female присвоить число 1
df.loc[df.Sex == 'male', 'Sex'] = 0
df.loc[df.Sex == 'female', 'Sex'] = 1

In [ ]:
# Замена значений в столбце Embarked на числовые
# Значению S присвоить число 0, значению C присвоить число 1, значению Q присвоить число 2
df.loc[df.Embarked == 'S', 'Embarked'] = 0
df.loc[df.Embarked == 'C', 'Embarked'] = 1
df.loc[df.Embarked == 'Q', 'Embarked'] = 2

In [ ]:
# Проверить результат замены значений
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",0,22.0,1,0,A/5 21171,7.2500,NaN,0
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",1,38.0,1,0,PC 17599,71.2833,C85,1
2,3,1,3,"Heikkinen, Miss. Laina",1,26.0,0,0,STON/O2. 3101282,7.9250,NaN,0
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",1,35.0,1,0,113803,53.1000,C123,0
4,5,0,3,"Allen, Mr. William Henry",0,35.0,0,0,373450,8.0500,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",0,27.0,0,0,211536,13.0000,NaN,0
887,888,1,1,"Graham, Miss. Margaret Edith",1,19.0,0,0,112053,30.0000,B42,0
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",1,21.5,1,2,W./C. 6607,23.4500,NaN,0
889,890,1,1,"Behr, Mr. Karl Howell",0,26.0,0,0,111369,30.0000,C148,1
890,891,0,3,"Dooley, Mr. Patrick",0,32.0,0,0,370376,7.7500,NaN,2

In [ ]:
# Определить признаки целевой переменной
X = df.drop(['Survived', 'Name', 'Ticket', 'Cabin'], axis=1)
y = df.Survived

In [ ]:
# Разделить данные на обучающую и тестовую выборки
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [ ]:
# Создание обучающей модели
model = DecisionTreeClassifier()

In [ ]:
# Передача в обучающую модель данных для построения прогноза
model.fit(X_train, y_train)

DecisionTreeClassifier()

In [ ]:
# Подготовка прогноза
model.predict(X_test)

array([0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1,
       0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0,
       0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0,
       1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0,
       0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1,
       0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       1, 0, 0, 1])

### Вывод результата

In [ ]:
# Оценка результата по метрике качества accuracy
print('Оценка качества по метрике accuracy:', accuracy_score(y_test, model.predict(X_test)))
print()

# Оценка результата по метрике качества precision
print('Оценка качества по метрике precision_score:', precision_score(y_test, model.predict(X_test)))
print()

# Оценка результата по метрике качества recall
print('Оценка качества по метрике recall_score:', recall_score(y_test, model.predict(X_test)))
print()

# Оценка результата по метрике качества f1
print('Оценка качества по метрике f1:', f1_score(y_test, model.predict(X_test)))
print()

Оценка качества по метрике accuracy: 0.7313432835820896

Оценка качества по метрике precision_score: 0.6756756756756757

Оценка качества по метрике recall_score: 0.6756756756756757

Оценка качества по метрике f1: 0.6756756756756757

Решение задачи при помощи Giga chat

Описание решение:

Для решения данной задачи необходимо разделить данные на группы по полу и классу обслуживания, найти медианные значения возраста для этих групп и заменить пропущенные значения соответствующими медианными значениями. Затем следует обучить модель классификатора деревьев решений и оценить её качество на тестовых данных с использованием различных метрик. Ниже приведен пример кода, реализующего данную задачу на Python с использованием библиотек Pandas и Scikit-Learn.

In [8]:
import pandas as pd
from sklearn import tree
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, f1_score, roc_auc_score, precision_recall_curve, confusion_matrix

# Чтение данных
url = 'https://raw.githubusercontent.com/ev-greshkina/DataAnalyst-educational-course/main/Titanic-Dataset.csv'
df = pd.read_csv(url)

df['Embarked'] = df['Embarked'].fillna('S') # заполняем NaN значением 'S'
df['Age'] = df['Age'].fillna(df.groupby(['Sex', 'Pclass'])['Age'].transform('median')) # заполняем NaN значением медианы
df['Survived'] = df['Survived'].astype('int')
df['Embarked'] = df['Embarked'].astype('category').cat.codes

df['Sex'] = df['Sex'].astype('category').cat.codes

# Теперь разобьем данные на обучающую и тестовую выборку:
X = df[['Pclass', 'Sex', 'Age', 'Embarked']]
y = df['Survived']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# Далее создадим модель DecisionTreeClassifier и обучим её:
clf = tree.DecisionTreeClassifier()
clf.fit(X_train, y_train)

# Проверим качество модели на обучающей и тестовой выборке:
preds_train = clf.predict(X_train)
accuracy_train = accuracy_score(y_train, preds_train)
precision_train, recall_train, _ = precision_recall_curve(y_train, preds_train)
roc_auc_train = roc_auc_score(y_train, preds_train)
print("Accuracy on training set:", accuracy_train)
print("ROC AUC on training set:", roc_auc_train)
print("F1 score on training set:", f1_score(y_train, preds_train))

preds_test = clf.predict(X_test)
accuracy_test = accuracy_score(y_test, preds_test)
precision_test, recall_test, _ = precision_recall_curve(y_test, preds_test)
roc_auc_test = roc_auc_score(y_test, preds_test)
print("Accuracy on testing set:", accuracy_test)
print("ROC AUC on testing set:", roc_auc_test)
print("F1 score on testing set:", f1_score(y_test, preds_test))

Accuracy on training set: 0.9069020866773676
ROC AUC on training set: 0.8833487940630798
F1 score on training set: 0.8632075471698113
Accuracy on testing set: 0.746268656716418
ROC AUC on testing set: 0.7266884719114018
F1 score on testing set: 0.6666666666666666

### Сторонний AI

In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import classification_report, accuracy_score, precision_score, recall_score, f1_score, roc_auc_score

# Загрузка датасета Titanic
url = 'https://raw.githubusercontent.com/ev-greshkina/DataAnalyst-educational-course/main/Titanic-Dataset.csv'
df = pd.read_csv(url)

# Преобразование категориальных переменных в числовые
df = pd.get_dummies(df, columns=['Sex', 'Embarked'], drop_first=True)

# Заменяем пропуски в Age на медианные значения по группам пол-класс обслуживания
df['Age'] = df.groupby(['Pclass', 'Sex_male'])['Age'].transform(lambda x: x.fillna(x.median()))

# Определение признаков и целевой переменной
X = df[['Pclass', 'Age', 'SibSp', 'Parch', 'Fare', 'Sex_male', 'Embarked_Q', 'Embarked_S']]
y = df['Survived']

# Разделение данных на обучающую и тестовую выборки
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Обучение DecisionTreeClassifier на заполненных данных
model = DecisionTreeClassifier(random_state=42)
model.fit(X_train, y_train)

# Прогнозирование
y_pred = model.predict(X_test)

# Оценка качества
accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)
roc_auc = roc_auc_score(y_test, model.predict_proba(X_test)[:, 1])

print(f'Accuracy: {accuracy:.4f}')
print(f'Precision: {precision:.4f}')
print(f'Recall: {recall:.4f}')
print(f'F1 Score: {f1:.4f}')
print(f'ROC AUC: {roc_auc:.4f}')
print('\nClassification Report:')
print(classification_report(y_test, y_pred))

Accuracy: 0.7877
Precision: 0.7368
Recall: 0.7568
F1 Score: 0.7467
ROC AUC: 0.7840

Classification Report:
              precision    recall  f1-score   support

           0       0.83      0.81      0.82       105
           1       0.74      0.76      0.75        74

    accuracy                           0.79       179
   macro avg       0.78      0.78      0.78       179
weighted avg       0.79      0.79      0.79       179